param(
    [switch]$Json
)

# Define paths relative to the repo root
$featureSpec = "specs\phase-1\001-in-memory-console-app.md"
$implPlan = "specs\phase-1\002-implementation-plan.md"
$specsDir = "specs"
$branch = "1-console-todo-app"

# Create the implementation plan file if it doesn't exist
if (-not (Test-Path $implPlan)) {
    # Create the directory if it doesn't exist
    $dir = Split-Path $implPlan -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force
    }
    
    $planContent = "# Implementation Plan for Phase I: In-Memory Python Console Todo Application

**Plan ID**: phase-1-implementation-plan
**Version**: 1.0
**Date**: December 31, 2025
**Author**: sharjeel
**GitHub Repository**: https://github.com/sharrjeel6636/hackathon-todo
**Spec Reference**: specs/phase-1/001-in-memory-console-app.md (Version 1.1)
**Constitution Adherence**: FULL - Zero manual code writing. All code generated exclusively by Claude Code via iterative spec refinement.

## Technical Context

[NEEDS CLARIFICATION: What Python version should be used?]
[NEEDS CLARIFICATION: What UV configuration is required?]
[NEEDS CLARIFICATION: How should the in-memory storage be implemented?]

## Constitution Check

Based on the project constitution, this implementation must:
- Follow Spec-Kit Plus slash commands with constitution adherence checks
- Use Claude Code exclusively for all code generation
- Maintain traceability and reproducibility of all artifacts
- Implement security and reliability measures appropriate for the phase
- Follow modularity and maintainability principles for iterative evolution
- Maintain progressive complexity from in-memory console to future phases

## Gates

- [ ] All technology choices align with Phase I constraints (Python 3.13+, UV, in-memory only)
- [ ] No manual code writing - all code must be generated by Claude Code
- [ ] Project structure matches requirements exactly
- [ ] Implementation plan adheres to constitution principles

## Phase 0: Research

Research tasks to resolve all NEEDS CLARIFICATION markers.

## Phase 1: Design & Contracts

- Data model design based on feature requirements
- API contracts (if applicable)
- Quickstart guide for development setup
- Agent context updates with new technologies

## Phase 2: Implementation Planning

- Break down implementation into atomic tasks
- Define success criteria for each task
- Plan verification steps
"
    $planContent | Out-File -FilePath $implPlan -Encoding UTF8
}

# Output JSON result if -Json switch is used
if ($Json) {
    $result = @{
        FEATURE_SPEC = $featureSpec
        IMPL_PLAN = $implPlan
        SPECS_DIR = $specsDir
        BRANCH = $branch
    } | ConvertTo-Json -Compress
    
    Write-Output $result
}